// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGghKHMGC5t1x_z4w9U95bBaSpI1mogVI',
    appId: '1:736882145582:web:128106210fc7a42a2162bf',
    messagingSenderId: '736882145582',
    projectId: 'fooddelivery-5afce',
    authDomain: 'fooddelivery-5afce.firebaseapp.com',
    storageBucket: 'fooddelivery-5afce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtI2c64AdFJWH7zl2oreYqrjglz8vw0TI',
    appId: '1:736882145582:android:8f64bdc95d67bdf02162bf',
    messagingSenderId: '736882145582',
    projectId: 'fooddelivery-5afce',
    storageBucket: 'fooddelivery-5afce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5n8rcSaNpHRSsBkPyTL_Vsk7NRvAEXV8',
    appId: '1:736882145582:ios:4ecb9388c9f9108b2162bf',
    messagingSenderId: '736882145582',
    projectId: 'fooddelivery-5afce',
    storageBucket: 'fooddelivery-5afce.firebasestorage.app',
    iosBundleId: 'com.augustoiseppe.deliveryAppWithBackend',
  );
}
